name: Build app and upload to S3 buckets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
        shell: bash

      - name: Perform linting
        run: yarn lint

      - name: Perform formatting
        run: yarn format

      - name: Run tests
        run: yarn test:run

      - name: Build App
        run: yarn build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_SESSION_TOKEN: ${{ vars.VITE_SESSION_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload build artifact to S3 bucket
        run: aws s3 sync ./dist ${{ secrets.S3_BUCKET_URI }} --cache-control no-cache --delete
